server:
  port: 9090

spring:
  application:
    name: rfms-system
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: ${nacos_host:127.0.0.1}:${nacos_port:8848}
        namespace: public
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
  config:
    import:
      - optional:nacos:datasource.yaml
#      - optional:nacos:common.yaml


storage:
  enabled: true
  config:
    # 存储类型：local、aliyun、tencent、qiniu、huawei、minio
    type: local
    domain: http://113.250.190.179:8899
  local:
    path: /opt/rfms/upload
