server:
  port: 8099

spring:
  application:
    name: rfms-new
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: ${nacos_host:127.0.0.1}:${nacos_port:8848}
        namespace: public
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
  config:
    import:
      - optional:nacos:datasource.yaml
      - optional:nacos:common.yaml
